src/advance_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from filebrowser.sites import site

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin/filebrowser/', site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('', include(('pages.urls', 'pages'), namespace='pages')),
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('bookmarks/', include(('bookmarks.urls', 'bookmarks'), namespace='bookmarks')),
    path('posts/', include(('posts.urls', 'posts'), namespace='posts')),
    path('api/posts/', include(('posts.api.urls', 'posts-api'), namespace='posts-api')),
    path('comments/', include(('comments.urls', 'comments'), namespace='comments')),
    path('api/comments/', include(('comments.api.urls',
                                   'comments-api'), namespace='comments-api')),
    path('likes/', include(('likes.urls', 'likes'), namespace='likes')),
    path('api/likes/', include(('likes.api.urls', 'likes-api'), namespace='likes-api')),
]

urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,
                      document_root=settings.STATIC_ROOT)

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL,
#                           document_root=settings.MEDIA_ROOT)
#     urlpatterns += static(settings.STATIC_URL,
#                           document_root=settings.STATIC_ROOT)

src/bookmarks/urls.py
from django.urls import path
from .views import add_to_bookmark, bookmarked_list, delete_from_bookmark

urlpatterns = [
    path('', bookmarked_list, name='bookmarked-list'),
    path('delete/<int:id>/', delete_from_bookmark, name='delete-from-bookmark'),
    # path('add/<int:post_id>', add_to_bookmark, name='add-to-bookmarke'),
    path('add/<int:id>/<model_type>/',
         add_to_bookmark, name='add-to-bookmarke'),
]

src/likes/urls.py
from django.urls import path
from.views import add_to_dislike, add_to_like

urlpatterns = [
    # path('like/<int:comment_id>/comment/',
    #      add_to_like, name='add-to-like-comment'),
    # path('like/<post_id>/post/', add_to_like, name='add-to-like-post'),
    path('dislike/<int:id>/<model_type>/',
         add_to_dislike, name='add-to-dislike'),
    path('like/<int:id>/<model_type>/', add_to_like, name='add-to-like'),
]

src/pages/urls.py
from django.urls import path
from .views import home_page, panel_admin

urlpatterns = [
    path('', home_page, name='home-page'),
    path('panel-admin/', panel_admin, name='panel-admin'),

]

src/posts/urls.py
from django.urls import path
from .views import post_detail, post_search_view, post_list, update_post, delete_post  # , post_like

urlpatterns = [
    path('search/', post_search_view, name='post-search'),
    path('', post_list, name='post-list'),
    path('<category_slug>/', post_list, name='category-list'),
    path('update/<id>/<slug>/', update_post, name='post-update'),
    path('delete/<id>/<slug>/', delete_post, name='post-delete'),
    path('detail/<post_id>/<post_slug>/', post_detail, name='post-detail'),
    # path('likes/<post_id>/<post_slug>/', post_like, name='post-like'),
]

src/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <title>TheEvent - Bootstrap Event Template</title>
  <meta content="width=device-width, initial-scale=1.0" name="viewport">
  <meta content="" name="keywords">
  <meta content="" name="description">

  <!-- Favicons -->
  <link href="{% static 'img/favicon.png' %}" rel="icon">
  <link href="{% static 'img/apple-touch-icon.png' %}" rel="apple-touch-icon">

  <!-- Google Fonts -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css"
    integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
  <link href="https://fonts.googleapis.com/css?family=Open+Sans:300,300i,400,400i,700,700i|Raleway:300,400,500,700,800"
    rel="stylesheet">


  <!-- Bootstrap CSS File -->

  <!-- Libraries CSS Files -->

  <!-- <link href="{% static 'lib/animate/animate.min.css" rel="stylesheet">
  <link href="{% static 'lib/venobox/venobox.css" rel="stylesheet">
  <link href="{% static 'lib/owlcarousel/assets/owl.carousel.min.css' %}" rel="stylesheet"> -->

  <!-- Main Stylesheet File -->
  <link href="{% static 'css/style.css' %}" rel="stylesheet" media="screen">
  <!-- <link href="https://bootswatch.com/4/litera/bootstrap.min.css" rel="stylesheet"> -->
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
    integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">

  <!-- =======================================================
    Theme Name: TheEvent
    Theme URL: https://bootstrapmade.com/theevent-conference-event-bootstrap-template/
    Author: BootstrapMade.com
    License: https://bootstrapmade.com/license/
  ======================================================= -->
</head>

<body>
  <!-- <body style="background: #27282e;color: #fff"> -->
  {% url 'pages:home-page' as home_page %}
  {% url 'pages:panel-admin' as panel_admin %}
  {% url 'posts:post-list' as post_list %}
  {% url 'posts:post-list' as post_list %}
  <!--==========================
    Header
  ============================-->
  <header id="header" style="background-color:#04091996">
    <div class="container">
      <div class="row justify-content-between">

        <div id="logo" class="pull-left">
          <!-- Uncomment below if you prefer to use a text logo -->
          <!-- <h1><a href="#main">C<span>o</span>nf</a></h1> -->
          <a href="{% url 'pages:home-page'%}" class="scrollto"><img src="{% static 'img/logo2.png' %}" alt=""
              title=""></a>
        </div>
        <nav id="nav-menu-container" class="rounded-pill" style="background-color:#04091996">

          <ul class="nav-menu">
            <!-- <li class="menu-active"><a href="#intro">Home</a></li>
          <li><a href="#about">About</a></li>
          <li><a href="#speakers">Speakers</a></li>
          <li><a href="#schedule">Schedule</a></li>
          <li><a href="#venue">Venue</a></li>
          <li><a href="#hotels">Hotels</a></li> -->
            {% if request.user.is_superuser or requset.user.is_staff %}
            <li class="{% if request.path == panel_admin %} menu-active {% endif %}"><a
                href="{% url 'pages:panel-admin' %}">پنل
                ادمین <span class="badge badge-danger">{{ comment_counter }}</span></a>
            </li>
            {% endif %}
            <li class="{% if request.path == post_list %} menu-active {% endif %}"><a href="#gallery">پنل کاربری</a>
            </li>
            <li class="{% if request.path == post_list %} menu-active {% endif %}"><a
                href="{% url 'posts:post-list' %}">پست ها</a></li>
            <li class="{% if request.path == home_page %} menu-active {% endif %}"><a
                href="{% url 'pages:home-page' %}">خانه</a></li>
            <li class="buy-tickets"><a href="{% url 'bookmarks:bookmarked-list' %}"><b>علاقه مندی ها</b></a></li>
          </ul>
        </nav><!-- #nav-menu-container -->
      </div>
    </div>
  </header><!-- #header -->

  <!--==========================
    Intro Section
  ============================-->
  {% block header %}
  {% endblock %}

  {% block home %}
  {% endblock %}

  {% block detail %}
  {% endblock %}
  <div class="container">
    <br><br>
    {% block content %}
    {% endblock %}
    <br><br>
  </div>
  <!--==========================
    Footer
  ============================-->
  <footer id="footer">
    <div class="footer-top">
      <div class="container">
        <div class="row">

          <div class="col-lg-3 col-md-6 footer-info">
            <img src="{% static 'img/logo2.png' %}" alt="TheEvenet">
            <p>In alias aperiam. Placeat tempore facere. Officiis voluptate ipsam vel eveniet est dolor et totam porro.
              Perspiciatis ad omnis fugit molestiae recusandae possimus. Aut consectetur id quis. In inventore
              consequatur ad voluptate cupiditate debitis accusamus repellat cumque.</p>
          </div>

          <div class="col-lg-3 col-md-6 footer-links">
            <h4>Useful Links</h4>
            <ul>
              <li><i class="fa fa-angle-right"></i> <a href="#">Home</a></li>
              <li><i class="fa fa-angle-right"></i> <a href="#">About us</a></li>
              <li><i class="fa fa-angle-right"></i> <a href="#">Services</a></li>
              <li><i class="fa fa-angle-right"></i> <a href="#">Terms of service</a></li>
              <li><i class="fa fa-angle-right"></i> <a href="#">Privacy policy</a></li>
            </ul>
          </div>

          <div class="col-lg-3 col-md-6 footer-links">
            <h4>Useful Links</h4>
            <ul>
              <li><i class="fa fa-angle-right"></i> <a href="#">Home</a></li>
              <li><i class="fa fa-angle-right"></i> <a href="#">About us</a></li>
              <li><i class="fa fa-angle-right"></i> <a href="#">Services</a></li>
              <li><i class="fa fa-angle-right"></i> <a href="#">Terms of service</a></li>
              <li><i class="fa fa-angle-right"></i> <a href="#">Privacy policy</a></li>
            </ul>
          </div>

          <div class="col-lg-3 col-md-6 footer-contact">
            <h4>Contact Us</h4>
            <p>
              A108 Adam Street <br>
              New York, NY 535022<br>
              United States <br>
              <strong>Phone:</strong> +1 5589 55488 55<br>
              <strong>Email:</strong> info@example.com<br>
            </p>

            <div class="social-links">
              <a href="#" class="twitter"><i class="fa fa-twitter"></i></a>
              <a href="#" class="facebook"><i class="fa fa-facebook"></i></a>
              <a href="#" class="instagram"><i class="fa fa-instagram"></i></a>
              <a href="#" class="google-plus"><i class="fa fa-google-plus"></i></a>
              <a href="#" class="linkedin"><i class="fa fa-linkedin"></i></a>
            </div>

          </div>

        </div>
      </div>
    </div>

    <div class="container">
      <div class="copyright">
        &copy; Copyright <strong>TheEvent</strong>. All Rights Reserved
      </div>
      <div class="credits">
        <!--
          All the links in the footer should remain intact.
          You can delete the links only if you purchased the pro version.
          Licensing information: https://bootstrapmade.com/license/
          Purchase the pro version with working PHP/AJAX contact form: https://bootstrapmade.com/buy/?theme=TheEvent
        -->
        Designed by <a href="https://bootstrapmade.com/">BootstrapMade</a>
      </div>
    </div>
  </footer><!-- #footer -->

  <a href="#" class="back-to-top"><i class="fa fa-angle-up"></i></a>

  <!-- JavaScript Libraries -->

  <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js"
    integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n"
    crossorigin="anonymous"></script>
  <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
  <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js"
    integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo"
    crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js"
    integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6"
    crossorigin="anonymous"></script>
  <!-- Contact Form JavaScript File -->
  <!-- <script src="{% static 'contactform/contactform.js' %}"></script> -->

  <!-- Template Main Javascript File -->
  <script src="{% static 'js/main.js' %}"></script>
  <script>
    $(function () {
      $('[data-toggle="tooltip"]').tooltip()
    })
  </script>
</body>

</html>