src/accounts/urls.py
from django.urls import path
from django.conf.urls import url
from django.contrib.auth.views import (
    PasswordChangeView,
    PasswordChangeDoneView,
    PasswordResetView,
    PasswordResetDoneView,
    PasswordResetConfirmView,
    PasswordResetCompleteView,

)
from .views import load_towns, profile_edit, activate, login_view, register_view, logout_view


urlpatterns = [
    path('ajax-city-list/', load_towns, name='ajax-load-towns'),
    path('login/', login_view, name='login-view'),
    path('logout/', logout_view, name='logout-view'),
    path('register/', register_view, name='register-view'),
    path('profile/edit/', profile_edit, name='profile-edit'),
    # path('activate/<uidb64>/<token>/', activate, name='activate'),
    url(r'^activate/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z]{1,13}-[0-9A-Za-z]{1,20})/$',
        activate, name='activate'),
    path('password-change/', PasswordChangeView.as_view()),
    path('password-change/done/', PasswordChangeDoneView.as_view()),
    path('password_reset/', PasswordResetView.as_view(
        template_name='accounts/password_reset_form.html',
        email_template_name='accounts/password_reset_email.html'), name='password_reset'),
    path('reset/<uidb64>/<token>/', PasswordResetConfirmView.as_view(
        template_name='accounts/password_reset_confirm.html'), name='password_reset_confirm'),
    path('password_reset/done/', PasswordResetDoneView.as_view(template_name='accounts/password_reset_done.html'),
         name='password_reset_done'),
    path('reset/done/', PasswordResetCompleteView.as_view(template_name="accounts/password_reset_complete.html"),
         name='password_reset_complete'),
]

src/advance_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from filebrowser.sites import site

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin/filebrowser/', site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('', include(('pages.urls', 'pages'), namespace='pages')),
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('bookmarks/', include(('bookmarks.urls', 'bookmarks'), namespace='bookmarks')),
    path('posts/', include(('posts.urls', 'posts'), namespace='posts')),
    path('api/posts/', include(('posts.api.urls', 'posts-api'), namespace='posts-api')),
    path('comments/', include(('comments.urls', 'comments'), namespace='comments')),
    path('api/comments/', include(('comments.api.urls',
                                   'comments-api'), namespace='comments-api')),
    path('likes/', include(('likes.urls', 'likes'), namespace='likes')),
    path('api/likes/', include(('likes.api.urls', 'likes-api'), namespace='likes-api')),
]

urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,
                      document_root=settings.STATIC_ROOT)

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL,
#                           document_root=settings.MEDIA_ROOT)
#     urlpatterns += static(settings.STATIC_URL,
#                           document_root=settings.STATIC_ROOT)

src/likes/urls.py
from django.urls import path
from.views import add_to_dislike, add_to_like

urlpatterns = [
    # path('like/<int:comment_id>/comment/',
    #      add_to_like, name='add-to-like-comment'),
    # path('like/<post_id>/post/', add_to_like, name='add-to-like-post'),
    path('dislike/<int:id>/<model_type>/',
         add_to_dislike, name='add-to-dislike'),
    path('like/<int:id>/<model_type>/', add_to_like, name='add-to-like'),
]

src/pages/urls.py
from django.urls import path
from .views import home_page, panel_admin

urlpatterns = [
    path('', home_page, name='home-page'),
    path('panel-admin/', panel_admin, name='panel-admin'),

]

src/accounts/models.py
from django.db import models
from django.core.validators import RegexValidator
# from django.contrib.auth.models import AbstractBaseUser, BaseUserManager, PermissionsMixin
from django.contrib.auth import get_user_model

User = get_user_model()


# # Create your models here.

# class UserManager(BaseUserManager):

#     def create_user(self, email, phone, password=None, **extra_fields):
#         """create and saves a new user"""
#          if not email:
#              raise ValueError('Users must have an email address')
#          if not phone:
#              raise ValueError('Users must have an phone number')
#         user = self.model(
#             email=self.normalize_email(email), **extra_fields)  # extra_fields baraye ezafe kardane field haye jadide
#         # passowd o nemishud tu khate bala guzasht chun bayad encript she
#         user.set_password(password)
#         user.save(using=self._db) #

#         return user

# def create_superuser(self, email, phone, password):
#     """
#     Creates and saves a superuser with the given email, date of
#     birth and password.
#     """
#     user = self.create_user(
#         email,
#         password=password,
#         phone=phone,
#     )
#     user.is_admin = True
#     user.save(using=self._db)
#     return user


# class User(AbstractBaseUser, PermissionsMixin):
#     """custome User model e ke beja username az email baraye login estefade mikone"""

#     email = models.EmailField(
#         max_length=255, unique=True, verbose_name='ایمیل')
#     phone_reg = RegexValidator(regex=r'[0][9][0-9]{9,9}$')
#     phone = models.CharField(
#         validators=[phone_reg],
#         max_length=11,
#         blank=True,
#         verbose_name='شماره تلفن'
#     )
#     is_active = models.BooleanField(default=True)
#     is_staff = models.BooleanField(default=False)
#     is_admin = models.BooleanField(default=False)
#     is_superuser = models.BooleanField(default=False)

#     objects = UserManager()

#     USERNAME_FIELD = 'email'
#     # REQUIRED_FIELDS = ['phone']
#     def __str__(self):
#       return self.email


# def has_perm(self, perm, obj=None):
#     "Does the user have a specific permission?"
#     # Simplest possible answer: Yes, always
#     return True

# def has_module_perms(self, app_label):
#     "Does the user have permissions to view the app `app_label`?"
#     # Simplest possible answer: Yes, always
#     return True

# @property
# def is_staff(self):
#     "Is the user a member of staff?"
#     # Simplest possible answer: All admins are staff
#     return self.is_admin


class City(models.Model):
    """modele Ostan"""
    name = models.CharField(max_length=120, verbose_name='نام استان')

    def __str__(self):
        return self.name


class Town(models.Model):
    """model e shahr ke ba city(ostan) relationship dare"""
    name = models.CharField(max_length=120, verbose_name='نام شهر')
    city = models.ForeignKey(City, related_name='town',
                             on_delete=models.CASCADE, verbose_name='نام استان')

    def __str__(self):
        return self.name


class Profile(models.Model):
    """profile baraye har user"""
    user = models.OneToOneField(
        User, related_name="profile", on_delete=models.CASCADE, verbose_name="نام کاربری")
    first_name = models.CharField(
        max_length=100, blank=True, verbose_name="نام")
    last_name = models.CharField(
        max_length=100, blank=True, verbose_name="نام خانوادگی")
    bio = models.CharField(max_length=500, blank=True,
                           verbose_name='درباره من')
    date_of_birth = models.DateField(
        blank=True, verbose_name="تاریخ تولد", null=True)
    # city = models.CharField(max_length=30, blank=True, verbose_name='شهر')
    town = models.ForeignKey(
        Town, related_name='profile', blank=True, null=True, on_delete=models.CASCADE)
    city = models.ForeignKey(
        City, related_name='profile', blank=True, null=True, on_delete=models.CASCADE)
    address = models.CharField(
        max_length=1000, blank=True, verbose_name='ادرس')
    phone_reg = RegexValidator(regex=r'[0][9][0-9]{9,9}$')
    phone = models.CharField(
        validators=[phone_reg],
        max_length=11,
        blank=True,
        verbose_name='شماره تلفن'
    )
    post_code = models.CharField(
        max_length=20, blank=True, verbose_name='کدپستی')
    image = models.ImageField(
        blank=True, upload_to='users_profile/img/%Y-%m-%d', verbose_name='اواتار')

    class Meta:
        verbose_name = "پروفایل"
        verbose_name_plural = "پروفایل ها"

    def __str__(self):
        return "پروفایل {}".format(self.user.username)

src/accounts/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponseRedirect, HttpResponse
from django.contrib import messages
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from .forms import ProfileUpdateForm, UserUpdateForm, LoginForm, RegisterForm
from .models import Town
# --------------------activation----------------
from .tasks import send_confirmation_email
from .tokens import account_activation_token
from django.contrib.sites.shortcuts import get_current_site
from django.utils.encoding import force_bytes, force_text
from django.utils.http import urlsafe_base64_encode, urlsafe_base64_decode
from django.template.loader import render_to_string
from django.contrib.auth import get_user_model
from urllib.parse import urlsplit


User = get_user_model()
# Create your views here.


def login_view(request):
    """faqat uniei ke login nakardan mitunan login konan"""
    next = request.GET.get('next')
    if request.user.is_authenticated:
        if next:
            return redirect(next)
        return redirect('accounts:profile-edit')
    form = LoginForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get('username')
        password = form.cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        login(request, user)
        if next:
            return redirect(next)
        else:
            return HttpResponseRedirect(request.META.get("HTTP_REFERER"))
    return render(request, 'accounts/login.html', {"form": form})


@login_required
def logout_view(request, *args, **kwargs):
    logout(request, *args, **kwargs)
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


def register_view(request):
    """
    faghat uni ke login nakarde mitune register kone
    amma accountesh ghyre faal mishe va ye email barash mifreste
    ta vaghti un email o active nakone is_active = False
    """
    if request.user.is_authenticated:
        return HttpResponseRedirect(request.META.get("HTTP_REFERER"))
    else:
        form = RegisterForm(request.POST or None)
        if form.is_valid():
            user = form.save(commit=False)
            user.is_active = False
            user.save()
            protocol = urlsplit(request.build_absolute_uri(None)).scheme
            current_site = get_current_site(request)
            message = render_to_string('accounts/active_email.html', {
                'user': user,
                'domain': current_site.domain,
                'uid': urlsafe_base64_encode(force_bytes(user.pk)),
                'token': account_activation_token.make_token(user),
                'protocol': protocol,
            })
            to_email = form.cleaned_data.get('email')
            send_confirmation_email.delay(message, to_email)
            return HttpResponse('لینک فعال سازی برای ایمیل شما ارسال شد')

    return render(request, 'accounts/register.html', {"form": form})


def activate(request, uidb64, token):
    """
    dar soorate mojud budane user id e user o decode mikone va check mikone 
    token ro ham hamrahe hamoon id e user check mikone
    age dorost bashe user is_active = True va login mishe 
    age na payame link na mootabar ast mide  
    """
    try:
        uid = force_text(urlsafe_base64_decode(uidb64))
        user = User.objects.get(pk=uid)
    except(TypeError, ValueError, OverflowError, User.DoesNotExist):
        user = None
    if user is not None and account_activation_token.check_token(user, token):
        user.is_active = True
        user.save()
        login(request, user)
        return redirect('pages:home-page')
        # return HttpResponse('اکانت شما فعال شد حال می توانید وارد شوید')
    else:
        return HttpResponse('لینک نا معتبر است.')


@login_required
def profile_edit(request):
    """ye form az tarkibe User o Profile"""
    if request.method == "POST":
        u_form = UserUpdateForm(request.POST, instance=request.user)
        p_form = ProfileUpdateForm(
            request.POST, request.FILES, instance=request.user.profile)
        if u_form.is_valid() and p_form.is_valid():
            u_form.save()
            p_form.save()
            # messages.success(request, f'پروفایل شما بروز رسانی شد')s
            return redirect('posts:post-list')

    else:
        u_form = UserUpdateForm(instance=request.user)
        p_form = ProfileUpdateForm(instance=request.user.profile)

    context = {
        'u_form': u_form,
        'p_form': p_form,

    }
    return render(request, 'accounts/profile_edit.html', context)


def load_towns(request):
    """
    city ro az form e edit-profile migire baad
    to ye html dg bessorate ajax field town o update mikone

    """
    city = request.GET.get('city')
    towns = Town.objects.filter(city=city)
    return render(request, 'accounts/city_town_list.html', {'towns': towns})

src/accounts/templates/accounts/active_email.html
<div>
    سلام {{ user.username }},
    برای فعال سازی اکانت خود وارد لینک زیر شوید :
</div>
<div>
    {{protocol}}://{{ domain }}{% url 'accounts:activate' uidb64=uid token=token %}
</div>

src/accounts/templates/accounts/city_town_list.html
<option value="">---------</option>
{% for town in towns %}
<option value="{{ town.id }}">{{ town.name }}</option>
{% endfor %}

src/accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div dir="rtl">
    <h4 class="text-right">ورود به سایت</h4>
    <form class="uniForm offset-md-9 text-right" action="." method="post">{% csrf_token %}
        {{ form|crispy }}
        <div class="row mt-5">
            <button class="btn btn-primary rounded-pill ml-5" type="submit">ورود</button>
            <a href="{% url 'password_reset' %}">رمز عبور را فراموش کرده ام</a>
        </div>
    </form>

</div>
{% endblock %}

src/accounts/templates/accounts/password_change_done.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div dir="rtl">
    <h4 class="text-right">تغییر رمز عبور</h4>
    <!-- <form action="." method="post">{% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-primary rounded-pill" type="submit">ثبت</button>
    </form> -->
    <div class="alert alert-success" role="alert">
        <h4 class="alert-heading">موفقیت امیز بود</h4>
        <p>پسورد شما با موفقیت تغییر کرد</p>
        <hr>
        <p class="mb-0"> بازگشت به <a href="{% url 'pages:home-page' %}"> صفحه اصلی</a></p>
    </div>
</div>
{% endblock %}

src/accounts/templates/accounts/password_change_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div dir="rtl">
    <h4 class="text-right">تغییر رمز عبور</h4>
    <form action="." method="post">{% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-primary rounded-pill" type="submit">ثبت</button>
    </form>
</div>
{% endblock %}

src/accounts/templates/accounts/password_reset_complete.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div dir="rtl">
    <h4 class="text-right">بازیابی رمز عبور</h4>
    <div class="alert alert-success text-right" role="alert">
        <h4 class="alert-heading">موفقیت امیز بود</h4>
        <p>رمز عبور شما با موفقیت تغییر کرد</p>
        <hr>
    </div>
</div>
{% endblock %}

src/accounts/templates/accounts/password_reset_confirm.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div>
    <h4 class="text-right mb-5">رمز عبور جدید را وارد کنید</h4>
    {% if validlink %}
    <form action="." method="post">{% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-primary rounded-pill" type="submit">ثبت</button>
    </form>
    {% else %}
    <div class="alert alert-danger col-md-8 offset-md-2" role="alert">
        <center>
            <h4 class="alert-heading">درخواست اشتباه</h4>
            <p>احتمالا قبلا از این لینک استفاده شده</p>
        </center>
        <hr>
        <p class="mb-0 offset-md-9"><a href="{% url 'password_reset' %}">بازیابی رمز عبور</a></p>
    </div>
    {% endif %}
</div>
{% endblock %}

src/accounts/templates/accounts/password_reset_done.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div>
    <h4 class="text-right mb-5">بازیابی رمز عبور</h4>
    <div class="alert alert-success col-md-8 offset-md-2" role="alert">
        <center>
            <h4 class="alert-heading">موفقیت امیز بود</h4>
            <p>لینکی برای بازیابی پسورد به ایمیل شما ارسال شد</p>
            <hr>
            <p class="mb-0">را هم چک کنید spam حتما داخل پوشه</a></p>
        </center>
    </div>
</div>
{% endblock %}

src/accounts/templates/accounts/password_reset_email.html
درخواست تغییر پسورد برای این ایمیل ({{ email }}) ارسال شده
برای تغییر روی لینک زیر کلیک کنید :
{{ protocol}}://{{ domain }}{% url 'password_reset_confirm' uidb64=uid token=token %}

src/accounts/templates/accounts/password_reset_form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div dir="rtl">
    <h4 class="text-right">بازیابی رمز عبور</h4>
    <form action="." method="post">{% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-primary rounded-pill" type="submit">ارسال لینک به ایمیل</button>
    </form>

</div>
{% endblock %}

src/accounts/templates/accounts/profile_edit.html
{% extends 'base.html' %}

{% block content %}

<form action="." method="post" id="profileForm" data-town-url="{% url 'accounts:ajax-load-towns' %}">{% csrf_token %}
    {{ u_form.as_p }}
    {{ p_form.as_p }}
    <button class="btn btn-primary" type="submit">sabt</button>
</form>
<div>
    <br>
    <img src="{{request.user.profile.image.url}}" alt="" style="width:100px;height:100px">
</div>

<script src="https://code.jquery.com/jquery-3.3.1.min.js"></script>
<script>
    $("#id_city").change(function () {
        var url = $("#profileForm").attr("data-town-url");  // get the url of the `load_cities` view
        var countryId = $(this).val();  // get the selected country ID from the HTML input

        $.ajax({                       // initialize an AJAX request
            url: url,                    // set the url of the request (= localhost:8000/hr/ajax/load-cities/)
            data: {
                'city': countryId       // add the country id to the GET parameters
            },
            success: function (data) {   // `data` is the return of the `load_cities` view function
                $("#id_town").html(data);  // replace the contents of the city input with the data that came from the server
            }
        });

    });
</script>

{% endblock %}

src/accounts/templates/accounts/register.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}


{% block content %}
<br>
<div class="col-12 col-md-8 offset-md-3 text-right">
    <h2 class="text-right">ثبت نام</h2>
    <br>


    <!-- <form action="{% url 'accounts:register-view' %}" class="needs-validation text-right" novalidate method="post">
        {% csrf_token %}
        <form class="needs-validation" novalidate>
            <div class="form-row">
                <div class="col-md-4 mb-4 offset-md-8 text-right">
                    <label for="validationCustomUsername">نام کاربری</label>
                    <div class="input-group text-right">
                        <div class="input-group-prepend">
                            <span class="input-group-text" id="inputGroupPrepend">@</span>
                        </div>
                        <input type="text" class="form-control" id="validationCustomUsername" placeholder="abcd"
                            name="username" value="{{username}}" aria-describedby="inputGroupPrepend" required>
                        <div class="invalid-feedback">
                            نام کاربری صحیح نیست
                        </div>
                    </div>
                </div>
            </div>

            <div class="form-row">
                <div class="col-md-4 mb-3 offset-md-4">
                    <label for="validationCustom02">نام خانوادگی</label>
                    <input type="text" class="form-control text-right" id="validationCustom02" placeholder="احمدی"
                        name="last_name" value="{{ last_name }}">
                    <div class="valid-feedback">
                        قابل قبول!
                    </div>
                </div>

                <div class="col-md-4 mb-3">
                    <label for="validationCustom01">نام</label>
                    <input type="text" class="form-control text-right" id="validationCustom01" name="first_name"
                        placeholder="احمد" value="{{ first_name }}">
                    <div class="valid-feedback">
                        قابل قبول!
                    </div>
                </div>
            </div>
            <div class="col-md-6 mb-3 offset-md-6">
                <div class="form-group col-md-6 offset-md-7">
                    <label for="inputEmail4">ایمیل</label>
                    <input type="email" class="form-control" id="inputEmail4" placeholder="example@info.com"
                        value="{{ email }}" name="email" required>
                </div>
            </div>

            <div class="col-md-6 mb-3 offset-md-6">
                <div class="form-group col-md-6 offset-md-7">
                    <label for="inputEmail4">تکرار ایمیل</label>
                    <input type="email" class="form-control" id="inputEmail4" placeholder="example@info.com"
                        value="{{ email2 }}" name="email2" required>
                </div>
            </div>

            <div class="col-md-6 mb-3 offset-md-6">
                <label for="inputPassword1">رمز عبور</label>
                <input type="password" class="form-control text-right" id="inputPassword1" name="passowrd1"
                    value="{{ passowrd1 }}" placeholder="رمز عبور" required>
            </div>
            <div class="col-md-6 mb-3 offset-md-6 ">
                <label for="inputPassword2">تکرار رمز عبور</label>
                <input type="password" class="form-control text-right" id="inputPassword2" name="passowrd2"
                    value="{{ passowrd2 }}" placeholder="رمز عبور" required>
            </div> -->




    <!-- <button class="btn btn-primary" type="submit">ثبت تغییرات</button>
    </form>

    <script>
        // Example starter JavaScript for disabling form submissions if there are invalid fields
        (function () {
            'use strict';
            window.addEventListener('load', function () {
                // Fetch all the forms we want to apply custom Bootstrap validation styles to
                var forms = document.getElementsByClassName('needs-validation');
                // Loop over them and prevent submission
                var validation = Array.prototype.filter.call(forms, function (form) {
                    form.addEventListener('submit', function (event) {
                        if (form.checkValidity() === false) {
                            event.preventDefault();
                            event.stopPropagation();
                        }
                        form.classList.add('was-validated');
                    }, false);
                });
            }, false);
        })();
    </script>
    <br>
    </form> -->



    <form class="text-right" method="POST">{% csrf_token %}
        <!-- {{ form_phone|crispy }} -->
        {{ form|crispy }}

        <br>
        <div class="form-group">
            <div class="form-check">
                <input class="form-check-input" type="checkbox" value="" id="invalidCheck" required>
                <label class="form-check-label" for="invalidCheck">
                    را خوانده ام و قبول دارم<button class="btn btn-link" data-toggle="modal"
                        data-target="#exampleModalScrollable">قوانین</button>
                </label>


                <div class="modal fade" id="exampleModalScrollable" tabindex="-1" role="dialog"
                    aria-labelledby="exampleModalScrollableTitle" aria-hidden="true">
                    <div class="modal-dialog modal-dialog-scrollable" role="document">
                        <div class="modal-content shadow-lg text-right">
                            <div class="modal-header text-right">
                                <h5 class="modal-title" id="exampleModalScrollableTitle">قوانین</h5>
                                <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                                    <span aria-hidden="true">&times;</span>
                                </button>
                            </div>
                            <div class="modal-body text-right">
                                Lorem ipsum dolor sit amet consectetur adipisicing elit. Tempora maxime facere,
                                aperiam expedita excepturi eos asperiores? Voluptate cum nostrum sed ut magni?
                                Dolores repellendus, aut nemo quas doloribus inventore reiciendis.
                                Lorem ipsum dolor sit amet consectetur adipisicing elit. Laborum modi beatae
                                facere nihil odit eos, odio quam nemo delectus maiores officiis commodi
                                aspernatur quae sequi ullam, optio magnam facilis? Corrupti?
                                Lorem ipsum dolor sit amet consectetur adipisicing elit. Modi esse aspernatur
                                dolorum debitis quaerat Lorem ipsum dolor sit amet consectetur adipisicing elit.
                                Nobis sequi quos accusantium sunt corporis. Impedit cum accusamus expedita quis
                                maxime libero rerum architecto, fugit autem facilis aliquid nemo aut quas! Lorem
                                ipsum dolor sit amet consectetur adipisicing elit. Vel iste similique dicta hic
                                debitis nobis cupiditate atque porro? Quia consectetur reprehenderit corrupti
                                ipsam accusamus ipsa ad beatae officiis tenetur vero? beatae tenetur distinctio,
                                perspiciatis ut laborum hic
                                inventore ea. Voluptatem nihil incidunt labore dolores vel corrupti!
                                Lorem ipsum dolor, sit amet consectetur adipisicing elit. Cupiditate alias,
                                praesentium ut nulla sunt est necessitatibus debitis iure nisi a. Laborum, rem.
                                Aspernatur exercitationem nesciunt accusantium dolore facere delectus explicabo?
                                Lorem ipsum, dolor sit amet consectetur adipisicing elit. Accusantium ea soluta
                                corporis ducimus nisi facilis odio doloribus non alias commodi nihil magni
                                deleniti aut praesentium quisquam rerum, harum debitis? Earum. Lorem ipsum dolor
                                sit amet, consectetur adipisicing elit. Eveniet, saepe! Recusandae tempore
                                reiciendis aut vero, deleniti dolorem consequuntur, rerum autem distinctio
                                soluta voluptas, libero aperiam nobis eaque debitis exercitationem! Soluta.
                            </div>
                            <div class="modal-footer">
                                <button type="button" class="btn btn-primary" data-dismiss="modal">بستن</button>
                            </div>
                        </div>
                    </div>
                </div>

                <div class="invalid-feedback">
                    برای تغییر پروفایل حتما باید قوانین را قبول کنید
                </div>
            </div>
        </div>
        <br>
        <button class="btn btn-warning" type="submit">ثبت نام</button>
    </form>

</div>
{% endblock %}