src/advance_blog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from filebrowser.sites import site

urlpatterns = [
    path('admin/', admin.site.urls),
    path('admin/filebrowser/', site.urls),
    path('api-auth/', include('rest_framework.urls')),
    path('tinymce/', include('tinymce.urls')),
    path('', include(('pages.urls', 'pages'), namespace='pages')),
    path('accounts/', include(('accounts.urls', 'accounts'), namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('bookmarks/', include(('bookmarks.urls', 'bookmarks'), namespace='bookmarks')),
    path('posts/', include(('posts.urls', 'posts'), namespace='posts')),
    path('api/posts/', include(('posts.api.urls', 'posts-api'), namespace='posts-api')),
    path('comments/', include(('comments.urls', 'comments'), namespace='comments')),
    path('api/comments/', include(('comments.api.urls',
                                   'comments-api'), namespace='comments-api')),
    path('likes/', include(('likes.urls', 'likes'), namespace='likes')),
    path('api/likes/', include(('likes.api.urls', 'likes-api'), namespace='likes-api')),
]

urlpatterns += static(settings.MEDIA_URL,
                      document_root=settings.MEDIA_ROOT)
urlpatterns += static(settings.STATIC_URL,
                      document_root=settings.STATIC_ROOT)

# if settings.DEBUG:
#     urlpatterns += static(settings.MEDIA_URL,
#                           document_root=settings.MEDIA_ROOT)
#     urlpatterns += static(settings.STATIC_URL,
#                           document_root=settings.STATIC_ROOT)

src/bookmarks/urls.py
from django.urls import path
from .views import add_to_bookmark, bookmarked_list, delete_from_bookmark

urlpatterns = [
    path('', bookmarked_list, name='bookmarked-list'),
    path('delete/<int:id>/', delete_from_bookmark, name='delete-from-bookmark'),
    # path('add/<int:post_id>', add_to_bookmark, name='add-to-bookmarke'),
    path('add/<int:id>/<model_type>/',
         add_to_bookmark, name='add-to-bookmarke'),
]

src/likes/urls.py
from django.urls import path
from.views import add_to_dislike, add_to_like

urlpatterns = [
    # path('like/<int:comment_id>/comment/',
    #      add_to_like, name='add-to-like-comment'),
    # path('like/<post_id>/post/', add_to_like, name='add-to-like-post'),
    path('dislike/<int:id>/<model_type>/',
         add_to_dislike, name='add-to-dislike'),
    path('like/<int:id>/<model_type>/', add_to_like, name='add-to-like'),
]

src/posts/api/urls.py
from django.urls import path
from .views import (
    PostListAPIView,
    PostDetailAPIView,
    PostDeleteAPIView,
    PostUpdateAPIView,
    PostCreateAPIView
)

urlpatterns = [
    path("", PostListAPIView.as_view(), name='post-list-api'),
    path("create/", PostCreateAPIView.as_view(), name='post-create-api'),
    path("detail/<int:pk>/", PostDetailAPIView.as_view(), name='post-detail-api'),
    path("update/<int:pk>/", PostUpdateAPIView.as_view(), name='post-update-api'),
    path("delete/<int:pk>/", PostDeleteAPIView.as_view(), name='post-delete-api'),
]

src/posts/urls.py
from django.urls import path
from .views import post_detail, post_search_view, post_list, update_post, delete_post  # , post_like

urlpatterns = [
    path('search/', post_search_view, name='post-search'),
    path('', post_list, name='post-list'),
    path('<category_slug>/', post_list, name='category-list'),
    path('update/<id>/<slug>/', update_post, name='post-update'),
    path('delete/<id>/<slug>/', delete_post, name='post-delete'),
    path('detail/<post_id>/<post_slug>/', post_detail, name='post-detail'),
    # path('likes/<post_id>/<post_slug>/', post_like, name='post-like'),
]

src/posts/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.contrib.postgres.fields import ArrayField
from django.contrib.contenttypes.models import ContentType
from django.contrib.contenttypes.fields import GenericRelation
from django.db.models import Count
from django.urls import reverse
from tinymce import HTMLField
from comments.models import Comments
from likes.models import LikeDislike
from rates.models import Rate
from usertrackers.models import UserTracker
from bookmarks.models import BookMark
import json


User = get_user_model()

# Create your models here.


class Category(models.Model):
    """ daste bandi e post ha"""
    title = models.CharField(
        max_length=120, db_index=True, verbose_name='عنوان دسته')
    slug = models.SlugField(max_length=120, blank=True, null=True,
                            unique=True, verbose_name="اسلاگ")
    description = models.TextField(
        blank=True, null=True, verbose_name='توضیحات')
    image = models.ImageField(
        blank=True, null=True, verbose_name='تصویر')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('posts:category-list', args=[self.slug])


class Post(models.Model):
    """model e post """
    author = models.ForeignKey(
        User, on_delete=models.CASCADE, verbose_name='نویسنده')
    title = models.CharField(max_length=120, verbose_name='عنوان')
    slug = models.SlugField(blank=True, max_length=100,
                            unique=True, verbose_name='اسلاگ')
    image = models.ImageField(
        verbose_name='تصویر عنوان', upload_to='posts/img/%Y-%m-%d')
    category = models.ManyToManyField(
        Category, related_name='post', verbose_name='دسته')
    content = HTMLField()
    tags = ArrayField(models.CharField(
        max_length=90), size=5, blank=True, null=True, verbose_name='تگ ها')
    previous = models.OneToOneField(
        'self', on_delete=models.SET_NULL, null=True, blank=True, related_name="nextpost", verbose_name='پست قبلی')
    read_time = models.TimeField(
        null=True, blank=True, verbose_name='زمان لازم برای خواندن پست')
    commetns = GenericRelation(Comments, related_name='post')
    rating = GenericRelation(Rate)
    likes = GenericRelation(LikeDislike, related_name='postlikes')
    usertracker = GenericRelation(UserTracker, related_name='postusertrakcer')
    published = models.BooleanField(default=True, verbose_name='پست شده')
    special = models.BooleanField(default=False, verbose_name='ویژه')
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)

    class Meta:
        """order barasase zamane sakht"""
        ordering = ('-created',)
        index_together = (('id', 'slug'),)
        verbose_name = 'پست'
        verbose_name_plural = 'پست ها'

    def __str__(self):
        """return kardane name nevisande va post"""
        return "پست {} توسط {}".format(self.title, self.author)

    @property
    def comments(self):
        """
        behtare vase har modeli ke mikhaym comment dashte bashe injuri ye property
        barash taarif konim.
        tu inja manzoor az self hamoon object haye Post e.
        age decorator e property o nazarim to view bayad joloye comments() bezarim
        """
        comments = Comments.objects.filter_by_model(
            instance=self).filter(approved=True)
        return comments

    def get_absolute_url(self):
        """reverse kardane be detail e post"""
        return reverse('posts:post-detail', args=[self.id, self.slug])

    def get_absolute_api_url(self):
        """reverse kardane be detail e post"""
        return reverse('posts-api:post-detail-api', args=[self.pk])

    def recommended_posts(self, request, same_post=None):
        """
        category haye pishnahadi bar assasse view e user to har post.
        baraye inke az tedad like ha baraye post estefade konim ye
        GenericRelation ba Modele LikeDislike zadam
        """
        # liked haro count mikone mirize to count bar assasse hamoon order mikone
        same_post = UserTracker.objects.recommended_list(
            request=request, instance=self).annotate(count=Count('likes__likedislike')).order_by('-count')
        # same_post = UserTracker.objects.recommended_list(
        #     request=request, instance=self).annotate(count=Count('likes__liked')).order_by('-count')
        return same_post

    @property
    def post_viewed(self):
        """tedad view haey ke post khurde"""
        viewed_item = UserTracker.objects.filter_by_model(
            instance=self).values_list('ip_address', flat=True).distinct()
        return viewed_item

    @property
    def post_rate(self, avg=0):
        """emtiaz dehi be post bar assasse rate entekhab shude (az 1 ta 5) taghsim bar tedad e user haey ke be in post emtiaz dadan"""
        average = Rate.objects.avg_rate(instance=self)
        return average

    @property
    def rated_post(self):
        user_rated = Rate.objects.filter_by_model(
            instance=self)
        return user_rated

    # def add_to_like_post(self, request, get_like=None):
    #     """like kardane post ha"""
    #     # get_like = LikeDislike.objects.create_for_instance_model(
    #     #     instance=self, request=request, liked=True, disliked=False)
    #     get_like = LikeDislike.objects.create_for_instance_model(
    #         instance=self, request=request, likedislike='like')
    #     return get_like

    # @property
    # def get_content_type(self):
    #     """
    #     baraye sakhtane form to Post bayad ContentType o begirim ta befahmim
    #     commenti ke dare neveshte mishe vase kodom post bere
    #     """

    #     content_type = ContentType.objects.get_for_model(self.__class__)
    #     return content_type

    # @property
    # def bookmarked_post(self):
    #     """check kardane inke post BookMark shude ya na"""
    #     book_marked = BookMark.objects.filter_by_model(
    #         instance=self)
    #     return book_marked

    # def add_to_bookmarked_post(self, user):
    #     """Add/Remove kardane bookmark e user baraye Post"""
    #     book_marked = BookMark.objects.create_by_instance_model(
    #         user=user, instance=self)
    #     return book_marked

    # def get_like_url(self):
    #     """function e like mesele get absloute url ke dg niaz nist to html id taarif konim"""
    #     return reverse('posts:post-like', args=[self.id, self.slug])

    # @property
    # def post_like(self):
    #     """neshun dadane post haye like shude"""
    #     # likes = LikeDislike.objects.filter_by_model(
    #     #     instance=self).filter(liked=True)
    #     likes = LikeDislike.objects.filter_by_model(
    #         instance=self).filter(likedislike='like')
    #     return likes

    # @property
    # def latest_posts(self):
    #     """3 ta post akhar"""
    #     posts = Post.objects.filter(
    #         published=True).order_by('-created')[:3]
    #     return posts

    # def save(self, *args, **kwargs):
    #     if not self.previous:
    #         self.previous = Post.objects.filter(
    #             id__lt=self.id).order_by('-id').first()
    #     super().save(*args, **kwargs)

src/posts/forms.py
from django import forms
from django.contrib.auth.models import User
from tinymce import TinyMCE

from .models import Post


class TinyMCEWidget(TinyMCE):
    def use_required_attribute(self, *args):
        return False
# class PostRateForm(forms.ModelForm):
#     class Meta:
#         model = Rate
#         fields = ("rating",)

# class SearchForm(forms.Form):
#     query = forms.CharField(
#         required=True)


class AddPostForm(forms.ModelForm):
    content = forms.CharField(label="افزونه", widget=TinyMCEWidget(
        attrs={'required': False, 'cols': 50, 'rows': 10}))

    class Meta:
        model = Post
        fields = ['author', 'title', 'image', 'category',
                  'content', 'tags', 'published', 'special']

        widgets = {
            'author': forms.HiddenInput,
        }

    # def __init__(self, *args, **kwargs):
    #     self.myuser = kwargs.pop('myuser', None)

    #     # print('userrrrrrrrrrrrrrr', self.myuser.email)
    #     super().__init__(*args, **kwargs)
    #     # print(self.fields['author'])
    #     try:
    #         # self.fields['author'].queryset = User.objects.filter(
    #         #     id=self.myuser.id)
    #         self.fields['author'] = self.myuser

    #     except:
    #         pass

src/posts/api/views.py
from rest_framework.generics import (
    ListAPIView,
    RetrieveAPIView,
    # UpdateAPIView,
    RetrieveUpdateDestroyAPIView,
    DestroyAPIView,
    CreateAPIView,
)
from rest_framework.permissions import (
    AllowAny,
    IsAdminUser,
    IsAuthenticated,
    IsAuthenticatedOrReadOnly,
)
from rest_framework.filters import (
    SearchFilter,
    OrderingFilter,
)


from django_filters.rest_framework import DjangoFilterBackend

from posts.models import Post
from .serializers import PostListSerializer, PostDetailSerializer, PostCreateSerializer
from .permissions import IsOwner
from .pagination import PostNumberPagination


class PostCreateAPIView(CreateAPIView):
    """sakhte yek Post besoorate API"""
    queryset = Post.objects.filter(published=True)
    serializer_class = PostCreateSerializer
    permission_classes = [IsAdminUser]

    def perform_create(self, serializer):
        """User e har posti ke create mishe request.user"""
        serializer.save(author=self.request.user)


class PostListAPIView(ListAPIView):
    """Listi az Model e Post besoorate API"""
    queryset = Post.objects.filter(published=True)
    serializer_class = PostListSerializer
    # pagination_class = PostNumberPagination
    filter_backends = [SearchFilter, DjangoFilterBackend, OrderingFilter]
    ordering_fields = ['title', 'author__username', 'special', 'created']
    filterset_fields = ['category__title', 'special', 'author__username']
    search_fields = ['title', 'content', 'category__title']


class PostDetailAPIView(RetrieveAPIView):
    """detail az Model e Post besoorate API"""
    queryset = Post.objects.filter(published=True)
    serializer_class = PostDetailSerializer


class PostUpdateAPIView(RetrieveUpdateDestroyAPIView):
    """update kardane yek post"""
    queryset = Post.objects.filter(published=True)
    serializer_class = PostDetailSerializer
    permission_classes = [IsOwner]

    # def perform_update(self, serializer):
    #     """User e har posti ke create mishe request.user"""
    #     serializer.save(author=self.request.user)


class PostDeleteAPIView(DestroyAPIView):
    """update kardane yek post"""
    queryset = Post.objects.filter(published=True)
    serializer_class = PostDetailSerializer
    permission_classes = [IsAdminUser]

src/posts/templates/posts/list.html
{% extends 'base.html' %}
{% load like_tags %}
{% block header %}
{% load bookmark_tags %}
{% load static %}
<img src="{% static 'media/list.jpg'%}" alt="" style="width: 100%;height: 750px">
{% endblock %}
{% block content %}

<div class="row justify-content-center">

    <div class="blog-page area-padding">
        <div class="row">

            <div class="col-lg-4 col-md-4 col-sm-4 col-xs-12">
                {% include "posts/sidebar.html" %}
            </div>
            <!-- End left sidebar -->
            <!-- Start single blog -->

            <section class="col-md-8 col-sm-8 col-xs-12">

                {% for post in posts %}
                <div class="row">
                    <div class="col-md-12 col-sm-12 col-xs-12">
                        <div class="single-blog border" dir="rtl">
                            <div class="single-blog-img">

                                <a href="{{ post.get_absolute_url }}">
                                    <div class="zoom cardtitle" style="position:relative">
                                        <img src="{{ post.image.url }}" class="card-img-top img-fluid"
                                            alt="{{ post.title }}" style="height: 500px;width: 810px">
                                        <h5 class="card-text text-light mb-0" style="background-color: rgba(0, 0, 0, 0.575);position:absolute; bottom:0;
                                                        padding:10px 20px; width:100%; text-align:center;">
                                            {{ post.title }}
                                            <div class="row justify-content-center" dir="ltr" style="height: 0%">
                                                <small class=" card-text text-light mr-5" style="height: 0%">
                                                    {{ post.comments.count }} <i class="far fa-comments"></i></small>
                                                <small class=" card-text text-light mr-5" style="height: 0%">
                                                    {% like_counter id=post.id model_type='post' %} <i
                                                        class="fas fa-heart"></i></small>
                                                <small class=" card-text text-light" style="height: 0%">
                                                    {{ post.post_viewed.count }} <i class="far fa-eye"></i></small>
                                            </div>

                                        </h5>

                                    </div>
                                    <!-- <img src="{{ post.image.url }}" alt="" style="height: 530px;width: 850px"> -->
                                </a>
                            </div>
                            <div class="row justify-content-around mt-4" dir="rtl">
                                <span class="comments-type mr-5">
                                    <img class="rounded-circle" src="{{ post.author.profile.image.url }}"
                                        style="height: 70px;width: 70px" alt="">
                                </span>
                                <span class="date-type mt-4 mr-3 offset-md-2">
                                    <i class="fa fa-calendar"></i>{{ post.author.username }}
                                </span>
                                <span class="mt-4 offset-md-2"><i class="far fa-calendar-alt"></i>
                                    {{ post.created|timesince }} پیش</span>
                                <span class="offset-md-1 mt-md-3">
                                    <a href="{% url 'bookmarks:add-to-bookmarke' id=post.id model_type='post' %}"
                                        class="text-dark" style="font-size: 24px">
                                        <i class="
                                        {% bookmark_btn_color id=post.id model_type='post' as bookmarkcolor %}
                                        {% if bookmarkcolor %}
                                        fas
                                        {% else %}
                                        far
                                        {% endif %}
                                fa-bookmark"></i>
                                    </a>

                                </span>
                            </div>
                            <hr>
                            <div class="blog-text mr-4 ml-2">
                                <small class="offset-md-6 text-muted">{% for x in post.category.all %}
                                    {% if post.category.all.count <= 1 %}
                                    {{ x.title }}
                                    {% elif post.category.all.count > 1 %}
                                    {% if forloop.first %}
                                    {% else %}
                                    |
                                    {% endif %}
                                    {{ x.title }}
                                    {% endif %}
                                    {% endfor %}
                                </small>
                                <p>
                                    {{ post.content|safe|truncatechars_html:10 }}
                                </p>
                                <br>
                                <span>
                                    <a class="offset-md-6 col-md-6 col-sm-6 col-xs-3" href="{{ post.get_absolute_url }}"
                                        id="rainbowbtn" style="left: 0px;right: 0px">مشاهده جزئیات
                                        پست</a>
                                </span>
                            </div>
                        </div>
                        <br>
                        <br>
                        {% endfor %}
                    </div>
                    <!-- End single blog -->

                    <!-- <div class="blog-pagination">
                                <ul class="pagination">
                                    <li><a href="#">&lt;</a></li>
                                    <li class="active"><a href="#">1</a></li>
                                    <li><a href="#">2</a></li>
                                    <li><a href="#">3</a></li>
                                    <li><a href="#">&gt;</a></li>
                                </ul>
                            </div> -->
                </div>
            </section>

        </div>

    </div>
    <!-- End Blog Area -->


    <div class="clearfix"></div>


</div>
<div>
    <div class="row">
        <hr class="col-md-8 col-sm-6 col-xs-6 px-4 mt-4 mr-0 text-dark">
        <h4
            class="col-md-3 col-sm-3 col-xs-3 pl-0 text-center mb-4 rounded-pill border border-danger border-1 p-2 bg-white">
            پیشنهاد
            به
            شما</h4>
    </div>
    <!-- <div class=" row justify-content-start" dir="rtl">

        {% for item in recommended %}
        <div class="col-md-3">
            <div class="card mb-3" style="width: 100%;">
                <a class="text-dark" href="{{ item.get_absolute_url }}">
                    <div class="zoom " style="position:relative">
                        <img src="{{ item.image.url }}" class="card-img-top" alt="{{ item.title }}"
                            style="height: 200px">
                        <h5 class="cardtitle card-text text-light mb-0" style="background-color: rgba(0, 0, 0, 0.575);position:absolute; bottom:0;
                                padding:10px 20px; width:100%; text-align:center;">
                            {{ item.title }}
                            <div class="row justify-content-around mt-3">
                                <small class=" card-text text-light mt-2">
                                    <small><small>
                                            {% for x in item.category.all %}
                                            {% if item.category.all.count <= 1 %}
                                            {{ x.title }}
                                            {% elif item.category.all.count > 1 %}
                                            {% if forloop.first %}
                                            {% else %}
                                            |
                                            {% endif %}
                                            {{ x.title }}
                                            {% endif %}
                                            {% endfor %}
                                        </small></small>
                                </small>
                            </div>

                        </h5>

                    </div>
                </a>




            </div>
        </div>
        {% empty %}
        {% endfor %}
</div> -->
</div>
<section dir="rtl">
    <div id="carouselExampleControls" class="carousel slide" data-ride="carousel">
        <div class="carousel-inner">

            <div class="carousel-item active ">
                <div class="row justify-content-start">
                    {% for item in recommended %}
                    <div class="col-md-3 col-sm-3 col-xs-3">
                        <a class="text-dark" href="{{ item.get_absolute_url }}">
                            <div class="zoom cardtitle" style="position:relative">
                                <img src="{{ item.image.url }}" class="card-img-top rounded-top" alt="{{ item.title }}"
                                    style="height: 230px">
                                <h5 class="card-text text-light mb-0" style="background-color: rgba(0, 0, 0, 0.575);position:absolute; bottom:0;
                                                padding:10px 20px; width:100%; text-align:center;">
                                    {{ item.title }}
                                    <div class="row justify-content-around mt-3">
                                        <small class=" card-text text-light mt-2">
                                            <small><small>
                                                    {% for x in item.category.all %}
                                                    {% if item.category.all.count <= 1 %}
                                                    {{ x.title }}
                                                    {% elif item.category.all.count > 1 %}
                                                    {% if forloop.first %}
                                                    {% else %}
                                                    |
                                                    {% endif %}
                                                    {{ x.title }}
                                                    {% endif %}
                                                    {% endfor %}
                                                </small></small>
                                        </small>
                                        <!-- <small class=" card-text text-light">تعدادلایک ها : {{ item.post_like.count }}</small>
                                                <small class=" card-text text-light">بازدید ها : {{ item.post_viewed.count }}</small> -->
                                        <!-- <img class="rounded-circle" src="{{ item.author.profile.image.url }}"
                                                    alt="{{ item.author.username }}" style="width: 40px;height: 40px;"> -->
                                    </div>

                                </h5>

                            </div>
                        </a>

                    </div>

                    {% if forloop.counter|divisibleby:4 and not forloop.last %}
                </div>
            </div>

            <div class="carousel-item">
                <div class="row justify-content-start">
                    {% endif %}
                    {% endfor %}
                </div>

            </div>


        </div>
        <a class="carousel-control-prev rounded-circle btn-outline-dark" href="#carouselExampleControls"
            style="margin-top: 90px;width: 50px;background-color: #f82249;height: 50px;" role="button"
            data-slide="prev">
            <span class="carousel-control-prev-icon" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="carousel-control-next rounded-circle btn-outline-dark" href="#carouselExampleControls"
            style="margin-top: 90px;width: 50px;background-color: #f82249;height: 50px;" role="button"
            data-slide="next">
            <span class="carousel-control-next-icon" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
</section>
{% endblock %}

src/posts/templates/posts/update_post.html
{% extends 'base.html' %}

{% block content %}
<br><br><br>

{% for field, errors in update_form.errors.items %}
{% for error in errors %}
{{ error }}

{% endfor %}
{% for error in field %}
{{error}}
{% endfor %}
{% endfor %}

<div class="row" dir="rtl">
    {{ update_form.media}}
    <form action="." method="post" enctype="multipart/form-data">
        {% csrf_token %}
        {{ update_form.author }}
        <p><label for="id_title">عنوان:</label> <input class="form-control" type="text" name="title"
                value="{{update_form.instance.title}}" maxlength="120" required="" id="id_title"></p>
        <p><label for="id_image" style="float: right">تصویر عنوان: </label> کنونی:

            <a href="{{update_form.instance.image.url}}"><img src="{{ update_form.instance.image.url }}"
                    style="height: 50px; width: 50px"></a><br>


            <div class="custom-file">
                <input type="file" class="custom-file-input" name="image" accept="image/*" id="id_image">
                <label class="custom-file-label" for="id_image">یک تصویر انتخاب کنید</label>
            </div>
        </p>

        <!-- {{ update_form.category}} -->
        <p><label for="id_category">دسته:</label>
            <div class="form-group">
                <select class="form-control" name="category" required id="id_category" multiple>
                    {% for category in categories %}
                    <option {% for cat in update_form.instance.category.all %} {% if cat == category %} selected
                        {% endif %}{% endfor %} value="{{category.id}}">
                        {{category.title}}</option>

                    {% endfor %}

                </select>
            </div>
        </p>


        {{update_form.content}}

        <p><label for="id_tags">تگ ها:</label> <input class="form-control" type="text" name="tags"
                value="{% for tag in update_form.instance.tags %}{{tag}}{% if not forloop.last %}, {% else %}{% endif %}{%empty%}{% endfor %}"
                id="id_tags"></p>
        <p><label for="id_published">منتشر شده</label>
            {{update_form.published}}</p>
        <p><label for="id_special">ویژه</label>
            {{update_form.special}}</p>
        <!-- {{ update_form.as_p }} -->
        <input class="btn btn-info" type="submit" value="ویرایش">
        <!-- <button class="btn btn-info" type="submit">ویرایش</button> -->

    </form>
</div>
{% endblock %}